### ISSUE TITLE
Overall Stats not displaying for Kinshasa

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/opencities#101]
![image](https://user-images.githubusercontent.com/1036189/47929688-34657c80-dea0-11e8-95ca-dcc03b34e369.png)

**Comment by cgiovando** [comment]
It must be some issue with how that widget is configured? Or on the API side?

Copying @tyrasd and @ppasq who should be able to debug

**Comment by gracedoherty** [comment]
We received a comment from a reader about OSM analytics not populating on the Accra page too. Not sure if related. If it's not, I can make this a separate issue.

Please prioritize any UI issues related to Open Cities, as we will be advertising both OpenDRI and Open Cities sites heavily at and after our Nov 14 mapathon.

Comment:
Hi ODRI Team, I have discovered that the OSM statistics (e.g. on https://opencitiesproject.org/accra/ --> mapping progress to date) won't show in my browser. After having checked any adblocking plugins, I have realised that the problem lies within the iFrame embed code: the URL of the OSM statistics tool needs to be changed from http to https, then the iFrame will load fine. Best, Bela

**Comment by gracedoherty** [comment]
I'll ask the user if the problem is persisting.

Any progress on the Kinshasa Overall Stats issue?

**Comment by vdeparday** [comment]
Accra is working but Kinshasa is still not working. @cgiovando @ppasq  Is that because the request is too big for Kinshasa ?

**Comment by ppasq** [comment]
Fixed while updating AoI polygons #124
