### ISSUE TITLE
OSM stats not loading on IE 11

### ISSUE THREAD

**Issue by gracedoherty** [GFDRR/opencities#103]
Checked for multiple cities pages.

![image](https://user-images.githubusercontent.com/42003495/48363471-fe7c8100-e673-11e8-9ec2-49938fa96707.png)

**Comment by ppasq** [comment]
I get a JS error: "Object doesn't support property or method 'find'". This method is not supported in IE and that might cause this problem. @tyrasd can you help on this? Even the embedded iframe does not work.

**Comment by cgiovando** [comment]
@tyrasd @ppasq we need to investigate this and figure out a solution. Seems to be a [common issue](https://www.google.com/search?q=Object+doesn%27t+support+property+or+method+%27find%27&oq=Object+doesn%27t+support+property+or+method+%27find%27), related to REACT requirements in IE11 and lower.

Maybe this fix? https://github.com/facebook/react/issues/8379#issuecomment-370686878

**Comment by vdeparday** [comment]
Can we make this one a very high priority ? We are circulating an update to all TTLs so it would be nice for it to work.

**Comment by cgiovando** [comment]
The issue may be with OSMA - checked here https://ie11.ieonchrome.com/#http://osm-analytics.org but that website doesn't provide much debugging information.

@tyrasd can you please investigate and report back?

**Comment by tyrasd** [comment]
> @tyrasd can you please investigate and report back?

I'll investigate this issue later today.

**Comment by tyrasd** [comment]
ok, the maps (which are included directly from osm-analytics.org) now work again.

Independently from this, the general "osm overall" stats, the "daily activity" bar graph and the "top contributors" report also don't load. As far as I can see this is because some javascript used in the opencitites website is using new javascript syntax that isn't supported by IE11 (e.g. the `cont` in https://github.com/GFDRR/opencities/blob/gh-pages/js/accra/app.js#L1, or the arrow functions and backtick string literals in the same file).

**Comment by ppasq** [comment]
Thanks @tyrasd.
@cgiovando should I open an issue on [OSMA charts](https://github.com/Vizzuality/osma-charts/issues)?

**Comment by cgiovando** [comment]
This is the more recent and main repo https://github.com/GFDRR/osm-analytics-charts

@ppasq is that something you can fix?

**Comment by tyrasd** [comment]
I'm not 100% sure, but I think it doesn't have much to do with the osm-analytics-charts code itself. It looks more like the code that would include the charts and data doesn't get called in IE11 in the first place. That code is in this repository here. Mostly, the files in https://github.com/GFDRR/opencities/blob/gh-pages/js/ (`app.js` in the city directories) are affected, because they use `const` and `Promise`s which aren't available in IE11.

**Comment by ppasq** [comment]
The app.js file is generated by [OSM Analytics Charts](https://github.com/GFDRR/osm-analytics-charts). So I wonder if OSMA Charts works on IE11.
In any case, we have tried to add support to IE11 and we have updated the [Accra page](https://opencitiesproject.org/accra/) for you to test. As you can see only one chart (OSM Daily Activity) still does not work. Any hint on how to solve this?
