### ISSUE TITLE
Give photo credit on homepage

### ISSUE THREAD

**Issue by gracedoherty** [GFDRR/opencities#52]
Each of the 3 photos used on the homepage need to be credited. Could be in small print in a corner of the photo, or in the footer? Wherever looks best.

Crowd with drone: © Mark Iliffe 
2 women holding GPS: Daniel Joseph / © American Red Cross
3 women with field papers: Daniel Joseph / © American Red Cross

**Comment by vdeparday** [comment]
I think for the first one you can have Mark Iliffe / © World Bank as I think technically it is World Bank since he was a World Bank consultant. Could we replace one of the two with a picture from Open Cities Africa directly from the kick-off or from the one coming from the various projects? That will have a better balance of sources this way.
